# Generated by Django 4.2.3 on 2023-07-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Student"), ("technician", "Technician")],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
