# Generated by Django 4.2.3 on 2023-07-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("technician", "Technician"),
                    ("admin", "admin"),
                ],
                max_length=20,
            ),
        ),
    ]
